#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"

function requires_laravel4() {
    [ $(jq --raw-output '.require["laravel/framework"]' < "$BUILD_DIR/composer.json") != "null" ]
}

function sets_framework_laravel4() {
    [ $(jq --raw-output '.extra.heroku.framework' < "$BUILD_DIR/composer.json") == "laravel4" ]
}

case "$1" in
    detect)
        if [ ! -f "$BUILD_DIR/composer.json" ]; then
            exit 1
        fi

        if requires_laravel4 || sets_framework_laravel4; then
            echo "-----> Detected Laravel 4 App"
            exit 0
        else
            exit 1
        fi
        ;;
    compile)
        echo "-----> Setting up Laravel 4 app"
        cp "$basedir/../conf/nginx/laravel4.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
        if [ -n "$CLEARDB_DATABASE_URL" ]; then
    		echo "-----> Writing database.php"
    		HEROKU_DB_USER=$(echo $CLEARDB_DATABASE_URL | cut -d: -f2 | cut -d/ -f3)
    		HEROKU_DB_PASS=$(echo $CLEARDB_DATABASE_URL | cut -d: -f3 | cut -d@ -f1)
    		HEROKU_DB_HOST=$(echo $CLEARDB_DATABASE_URL | cut -d: -f3 | cut -d@ -f2 | cut -d/ -f1)
    		HEROKU_DB_NAME=$(echo $CLEARDB_DATABASE_URL | cut -d: -f3 | cut -d@ -f2 | cut -d/ -f2 | cut -d\? -f1)
    		cp -f "$basedir/../conf/frameworks/laravel4/database.php" "$BUILD_DIR/app/config/database.php"
    		sed -i "s/DB_HOST/$HEROKU_DB_HOST/g;s/DB_USER/$HEROKU_DB_USER/g;s/DB_PASS/$HEROKU_DB_PASS/g;s/DB_NAME/$HEROKU_DB_NAME/g" "$BUILD_DIR/app/config/database.php"
        fi
        ;;
esac
